### ISSUE TITLE
Create page for Action Groups

### ISSUE THREAD

**Issue by vincelee888** [StreetSupport/mhp#1]
create a new page for the Action Groups, taking content from: https://charter.streetsupport.net/join-action-group/

include:

whatIs:
* title:text
* body:markdown

howDoesItWork:
* title:text
* body:markdown

then for each individual action group:
  - title:text
  - body:markdown
  - id:text (to hook back into SSN)

link to this new page, from home page "how to get involved" section

when creating action group collection, have a quick look into how Hugo structures sub-collections, to allow automated nav generation, and data re-use - just do it manually if difficult!

**Comment by anywhereiromy** [comment]
I am working on this and will try and submit a pull request this evening.

**Comment by anywhereiromy** [comment]
Let me know if you want me to give you what I have already completed though

**Comment by vincelee888** [comment]
Hi Romy

If you can finish it soon, then it can wait

Cheers!

**Comment by vincelee888** [comment]
Hi @anywhereiromy 

Take a look at this repo to see how to structure a section with sub pages: https://github.com/StreetSupport/real-change-seed/tree/wigan-and-leigh/hugo

In this one, we have a Stories listing page (index), with individual stories underneath it

**Comment by anywhereiromy** [comment]
Thanks I was struggling a bit last night. Will have another shot after work tonight!

Sent from my iPhone

On 5 Apr 2019, at 12:41, Vince Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @anywhereiromy<https://github.com/anywhereiromy>

Take a look at this repo to see how to structure a section with sub pages: https://github.com/StreetSupport/real-change-seed/tree/wigan-and-leigh/hugo

In this one, we have a Stories listing page (index), with individual stories underneath it

**Comment by anywhereiromy** [comment]
Not sure if I have managed to do what you wanted here. Let me know if you didn't get my pull request, as I haven't done one in a long time!
