### ISSUE TITLE
create page for each individual action group

### ISSUE THREAD

**Issue by vincelee888** [StreetSupport/mhp#4]
create a template for the action group details page, to include:

- title:text
- description:text
- co-chair names:text
- what the groups aims are:markdown
- what they have done so far:markdown
- what they hope to do next:markdown
- what they need / blockers:markdown

**Comment by anywhereiromy** [comment]
I think I accidentally created a lot of md files for these under the archive folder in action-groups

**Comment by vincelee888** [comment]
closing this until get content from Dee
